### ISSUE TITLE
Chef spun up a broken deployment. 

### ISSUE THREAD

**Issue by AlexHockey** [Metaswitch/chef#254] opened 2016-01-15 17:57 UTC
I just spun up a deployment with chef. This appeared to go fine with no errors in chef. However the deployment was really broken: 

*  Several processes refused to start (homestead, homestead-prov, homer). 
*  Ellis had the wrong URIs (all URIs had the domain `cw-ngv.com`instead of my actual domain).
*  The `clearwater-socket-factory` whitelist (/etc/clearwater-socket-factory/management.d) files were not in place.

It looks a lot like `clearwater-infrastructure` had never been run on these boxes (or it had been run before the software was installed), but `/var/log/dpkg.log` looks clean.

**Comment by eleanor-merry** [comment] 2016-01-19 16:05
This was caused by a couple of bugs in the new queue-manager - fixed in https://github.com/Metaswitch/clearwater-etcd/pull/246 and https://github.com/Metaswitch/clearwater-etcd/pull/248. The ellis numbers issue is covered by https://github.com/Metaswitch/ellis/issues/155

**Closed by eleanor-merry** 2016-01-19 16:05 UTC
Labels: bug, medium-priority
